version: '3'

services:
  transfer:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - '3100:3100'
    env_file:
      - .ENV
    image: transfer:1.00
    container_name: transfer
